/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "田一一",
  "description": "no description",
  "base": "/daily/",
  "headTags": [],
  "pages": [
    {
      "title": "一月份",
      "frontmatter": {},
      "regularPath": "/January.html",
      "relativePath": "January.md",
      "key": "v-24e975f4",
      "path": "/January.html",
      "headers": [
        {
          "level": 2,
          "title": "2021-1-26",
          "slug": "_2021-1-26"
        }
      ]
    },
    {
      "title": "Daily Record",
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-83c82b72",
      "path": "/"
    },
    {
      "title": "Something Else",
      "frontmatter": {},
      "regularPath": "/others/",
      "relativePath": "others/README.md",
      "key": "v-78ceb0ec",
      "path": "/others/"
    },
    {
      "title": "噩梦",
      "frontmatter": {},
      "regularPath": "/others/nightmare.html",
      "relativePath": "others/nightmare.md",
      "key": "v-a0181932",
      "path": "/others/nightmare.html"
    }
  ],
  "themeConfig": {
    "sidebar": {
      "/others/": [
        "",
        "nightmare"
      ],
      "/": [
        "",
        "January"
      ]
    },
    "nav": [
      {
        "text": "其他",
        "link": "/others/"
      },
      {
        "text": "每日记录",
        "link": "/"
      }
    ]
  }
}