/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "田一一",
  "description": "no description",
  "base": "/press/",
  "headTags": [],
  "pages": [
    {
      "title": "每日记录",
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-25995407",
      "path": "/",
      "headers": [
        {
          "level": 2,
          "title": "一月份",
          "slug": "一月份"
        },
        {
          "level": 3,
          "title": "2021-1-26",
          "slug": "_2021-1-26"
        }
      ]
    },
    {
      "title": "其他",
      "frontmatter": {},
      "regularPath": "/others/",
      "relativePath": "others/README.md",
      "key": "v-2f7a014a",
      "path": "/others/",
      "headers": [
        {
          "level": 2,
          "title": "噩梦",
          "slug": "噩梦"
        }
      ]
    }
  ],
  "themeConfig": {
    "sidebar": "auto",
    "nav": [
      {
        "text": "其他",
        "link": "/others/"
      },
      {
        "text": "每日记录",
        "link": "/"
      }
    ]
  }
}